repos:
-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
-   repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/kynan/nbstripout
    rev: master
    hooks:
    -   id: nbstripout
-   repo: local
    hooks:
    # FYI https://gitlab.com/daverona/pre-commit/cpp
    -   id: cpplint
        name: cpplint
        description: Run `cpplint` against C/C++ header and source files
        language: python
        files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
        entry: cpplint
        args: [
            "--verbose=3",
            "--counting=toplevel",
            "--filter=-legal/copyright",
            "--linelength=88"
            ]
