name: mumaxplus
channels:
  - conda-forge
dependencies:
  # required
  - python=3.13
  - conda-build
  - pytest
  - matplotlib
  - numpy
  - cmake=4.0.0
  - scipy

  # code checks
  - black
  - cpplint
  - flake8
  - flake8-docstrings
  - isort # check that imports are in the right order
  - pre-commit
  - pip
  - pip:
      - clang-format

  # optional
  - ipython
  - jupyter
  - ipywidgets
  - pyvista
  - pillow  # should be contained in matplotlib
  - pandas
  - pip:
      - pyovf

  # documentation generation
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
